// Generated by `fumadocs-mdx` at the project root (`<repo>/.source`).
// Fumadocs MDX v15 codegen emits per-environment files (server.ts,
// browser.ts, dynamic.ts) instead of a barrel index, so we import
// the server entry directly. The `@/*` alias only maps to `src/*`,
// so a relative path is the cleanest resolution.
// Note: `.source/` is gitignored — codegen output, regenerated by
// `createMDX()` in `next.config.ts` on dev/build.
import { docs } from "../../.source/server";
import { loader } from "fumadocs-core/source";

// Fumadocs source loader. Reads from generated `.source` directory at the
// project root (created by `fumadocs-mdx` next plugin during build/dev).
// URL base = `/docs` — the docs route is mounted at `app/docs/`.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
