"use client";

import { useState, useMemo } from "react";
import { Card, CardHeader } from "@/components/card";
import {
  calculateDepositInterest,
  type DepositInputs,
} from "@/lib/calculations/deposit-interest";
import { DEPOSIT_INTEREST_RATES } from "@/lib/constants/tools/deposit-rates";
import { formatCurrencyCents, formatPercent } from "@/lib/format-utils";
import { trackEvent } from "@/components/analytics";

function Row({
  label,
  value,
  note,
  bold,
  accent,
}: {
  label: string;
  value: string;
  note?: string;
  bold?: boolean;
  accent?: boolean;
}) {
  return (
    <div className="flex justify-between items-baseline py-2 border-b border-card-border last:border-0">
      <div>
        <span className={bold ? "text-sm font-medium text-foreground" : "text-sm text-muted"}>
          {label}
        </span>
        {note && <span className="block text-[11px] text-muted/70 mt-0.5">{note}</span>}
      </div>
      <span
        className={`font-mono text-sm tabular-nums ${
          accent ? "text-accent font-semibold text-base" : bold ? "font-semibold text-foreground" : "text-foreground"
        }`}
      >
        {value}
      </span>
    </div>
  );
}

function generatePDF(result: ReturnType<typeof calculateDepositInterest>) {
  import("jspdf").then(({ default: jsPDF }) => {
    const doc = new jsPDF();
    const margin = 20;
    let y = margin;

    doc.setFontSize(18);
    doc.text("Alberta Security Deposit Interest Report", margin, y);
    y += 12;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Alberta Pulse Check — albertapulsecheck.ca", margin, y);
    doc.text(`Generated: ${new Date().toLocaleDateString("en-CA")}`, margin, y + 5);
    y += 16;

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Summary", margin, y);
    y += 8;

    doc.setFontSize(10);
    const lines = [
      `Security deposit: ${formatCurrencyCents(result.depositAmount)}`,
      `Tenancy period: ${result.tenancyStartDate} to ${result.tenancyEndDate}`,
      `Duration: ${result.totalDays} days`,
      `Total interest owed: ${formatCurrencyCents(result.totalInterest)}`,
      `Total to return: ${formatCurrencyCents(result.totalOwed)}`,
    ];
    for (const line of lines) { doc.text(line, margin, y); y += 6; }
    y += 8;

    doc.setFontSize(12);
    doc.text("Year-by-Year Breakdown", margin, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Period", margin, y);
    doc.text("Year", margin + 50, y);
    doc.text("Rate", margin + 70, y);
    doc.text("Days", margin + 90, y);
    doc.text("Interest", margin + 110, y);
    y += 2;
    doc.line(margin, y, margin + 140, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    for (const row of result.yearBreakdown) {
      doc.text(`${row.periodStart} – ${row.periodEnd}`, margin, y);
      doc.text(String(row.year), margin + 50, y);
      doc.text(formatPercent(row.rate, 2), margin + 70, y);
      doc.text(String(row.daysInPeriod), margin + 90, y);
      doc.text(formatCurrencyCents(row.interest), margin + 110, y);
      y += 6;
      if (y > 270) { doc.addPage(); y = margin; }
    }

    y += 6;
    doc.line(margin, y, margin + 140, y);
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.text(`Total interest: ${formatCurrencyCents(result.totalInterest)}`, margin, y);

    y += 16;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Rates from Alberta.ca. Interest is simple (not compound), calculated on original deposit.", margin, y);
    doc.text("This is an estimate — consult the Residential Tenancies Act for legal requirements.", margin, y + 5);

    trackEvent("pdf_download", "tools", "deposit_calculator");
    doc.save("alberta-deposit-interest-report.pdf");
  });
}

export function DepositCalculator() {
  const today = new Date().toISOString().split("T")[0];
  const oneYearAgo = new Date(Date.now() - 365 * 86_400_000).toISOString().split("T")[0];

  const [depositAmount, setDepositAmount] = useState("1200");
  const [startDate, setStartDate] = useState(oneYearAgo);
  const [endDate, setEndDate] = useState(today);

  const result = useMemo(() => {
    const inputs: DepositInputs = {
      depositAmount: Number(depositAmount) || 0,
      tenancyStartDate: startDate,
      tenancyEndDate: endDate,
    };
    if (new Date(startDate) >= new Date(endDate)) return null;
    trackEvent("calculator_use", "tools", "deposit_calculator");
    return calculateDepositInterest(inputs);
  }, [depositAmount, startDate, endDate]);

  return (
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
      {/* Left column */}
      <div className="space-y-4">
        <Card>
          <CardHeader title="Deposit Details" />
          <div className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-muted mb-1">Security deposit amount</label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-muted">$</span>
                <input type="number" value={depositAmount} onChange={(e) => setDepositAmount(e.target.value)} min={0} className="w-full pl-7 pr-3 py-2 text-sm rounded-lg bg-background border border-card-border text-foreground focus:outline-none focus:border-accent" />
              </div>
              <p className="text-[11px] text-muted/70 mt-1">Max deposit is one month&apos;s rent in Alberta</p>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className="block text-xs font-medium text-muted mb-1">Tenancy start date</label>
                <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-full px-3 py-2 text-sm rounded-lg bg-background border border-card-border text-foreground focus:outline-none focus:border-accent" />
              </div>
              <div>
                <label className="block text-xs font-medium text-muted mb-1">Tenancy end date</label>
                <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-full px-3 py-2 text-sm rounded-lg bg-background border border-card-border text-foreground focus:outline-none focus:border-accent" />
              </div>
            </div>
          </div>
        </Card>

        {result ? (
          <>
            <Card>
              <CardHeader title="Year-by-Year Breakdown" />
              {result.yearBreakdown.map((row) => (
                <Row key={row.year + row.periodStart} label={`${row.year}`} value={formatCurrencyCents(row.interest)} note={`${formatPercent(row.rate, 2)} rate — ${row.daysInPeriod} days`} />
              ))}
              <Row label={`Total (${result.totalDays} days)`} value={formatCurrencyCents(result.totalInterest)} bold accent />
            </Card>

            <Card>
              <CardHeader title="Deposit Return Summary" />
              <Row label="Original deposit" value={formatCurrencyCents(result.depositAmount)} />
              <Row label="Interest owed" value={`+${formatCurrencyCents(result.totalInterest)}`} />
              <Row label="Total to return to tenant" value={formatCurrencyCents(result.totalOwed)} bold accent />
            </Card>
          </>
        ) : (
          <Card>
            <p className="text-sm text-muted text-center py-4">
              Enter a valid deposit amount and date range to see results.
            </p>
          </Card>
        )}

        {/* Rate reference table */}
        <Card>
          <CardHeader title="Historical Interest Rates" />
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-muted">
                  <th className="pb-2 font-medium text-xs">Year</th>
                  <th className="pb-2 font-medium text-xs text-right">Rate</th>
                </tr>
              </thead>
              <tbody>
                {Object.entries(DEPOSIT_INTEREST_RATES)
                  .sort(([a], [b]) => Number(b) - Number(a))
                  .map(([year, rate]) => (
                    <tr key={year} className="border-t border-card-border">
                      <td className="py-1.5 text-foreground">{year}</td>
                      <td className="py-1.5 text-right font-mono text-foreground">{formatPercent(rate, 2)}</td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
          <p className="text-[10px] font-mono text-muted/60 mt-3">
            Source: alberta.ca — Rate = ATB Financial cashable 1-year GIC rate (Nov 1 prior year) minus 3%.
          </p>
        </Card>

        {/* SEO content */}
        <Card>
          <div className="prose-sm space-y-3 text-sm text-muted">
            <h2 className="text-foreground text-base font-semibold">Alberta Security Deposit Rules</h2>
            <p>
              Under the Residential Tenancies Act, Alberta landlords can collect a maximum
              security deposit of one month&apos;s rent. Interest must be paid at the rate
              set annually by the Alberta government.
            </p>
            <h3 className="text-foreground text-sm font-semibold">When is interest paid?</h3>
            <p>
              Interest is paid annually on the tenancy anniversary, or when the deposit is
              returned. The interest is simple — calculated on the original deposit only.
            </p>
            <h3 className="text-foreground text-sm font-semibold">Deposit return timeline</h3>
            <p>
              Landlords must return the deposit (plus interest) within 10 days of move-out,
              unless deductions are claimed. If deductions are claimed, a written statement
              is required within 10 days and the balance within 30 days.
            </p>
            <p className="text-[10px] font-mono text-muted/60">
              Source: alberta.ca/annual-security-deposit-interest-rate. Updated for 2026.
            </p>
          </div>
        </Card>
      </div>

      {/* Right column */}
      <div className="space-y-4">
        {result && (
          <Card className="border-accent/30">
            <CardHeader title="Amount to Return" />
            <Row label="Original deposit" value={formatCurrencyCents(result.depositAmount)} />
            <Row label="Interest owed" value={formatCurrencyCents(result.totalInterest)} />
            <Row label="Total to return" value={formatCurrencyCents(result.totalOwed)} bold accent />
          </Card>
        )}

        {result && (
          <button
            onClick={() => generatePDF(result)}
            className="w-full py-2.5 px-4 rounded-lg font-medium text-sm transition-colors cursor-pointer bg-accent text-white hover:bg-accent-hover"
          >
            Download PDF Report
          </button>
        )}

        <Card className="bg-accent-amber/5 border-accent-amber/20">
          <p className="text-sm font-medium text-foreground mb-1">Landlord obligations</p>
          <p className="text-xs text-muted leading-relaxed">
            Under Alberta&apos;s Residential Tenancies Act, landlords must pay
            interest on security deposits annually or when the deposit is returned.
            The deposit must be returned within 10 days of move-out.
          </p>
        </Card>
      </div>
    </div>
  );
}
