import type { Metadata } from "next";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { Card } from "@/components/card";
import {
  Home,
  Target,
  MapPin,
  Building,
  Store,
  ArrowRight,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Alberta Real Estate — Market Intelligence & Opportunities",
  description:
    "Alberta real estate data — prospect leads, market intelligence, neighbourhood analysis, development pipeline, rental trends, and commercial activity. Built for realtors, investors, and developers.",
};

const pages = [
  {
    href: "/real-estate/prospects",
    icon: Target,
    title: "Prospect Leads",
    description:
      "Algorithmically-identified opportunities: equity-rich sellers likely to list, teardown-ready lots, vacant land with development potential, renovation upside candidates, and areas with development permit surges. These are generated by cross-referencing assessment data, permit activity, and property age across municipalities.",
    sources: "ArcGIS, Edmonton Open Data, municipal APIs",
  },
  {
    href: "/real-estate/market",
    icon: Home,
    title: "Market Intel",
    description:
      "The big picture — housing starts, property assessments, permit volumes, mortgage rates, and mill rate trends. If Prospect Leads tells you where to look, Market Intel tells you whether the overall conditions support buying, selling, or waiting.",
    sources: "Bank of Canada, Statistics Canada, Edmonton Open Data, ArcGIS",
  },
  {
    href: "/real-estate/neighbourhoods",
    icon: MapPin,
    title: "Neighbourhoods",
    description:
      "Micro-level signals from cross-analyzing permits, development activity, and assessment changes at the neighbourhood level. Identifies transformation zones (areas flipping from single-family to multi-unit), teardown corridors, renovation ROI hotspots, and places where commercial and residential uses are converging.",
    sources: "Municipal permit & assessment data",
  },
  {
    href: "/real-estate/pipeline",
    icon: Building,
    title: "Development Pipeline",
    description:
      "CMHC (Canada Mortgage and Housing Corporation) housing starts, completions, and units under construction for Alberta's major metro areas. The pipeline tells you what supply is coming — a surge in starts today means inventory hitting the market in 12–18 months. Watch completions vs. starts for absorption health.",
    sources: "Statistics Canada (CMHC series)",
  },
  {
    href: "/real-estate/rental",
    icon: Home,
    title: "Rental Intel",
    description:
      "CMHC vacancy rates and average rents by unit type (bachelor, 1-bed, 2-bed, 3-bed+) across Alberta census metropolitan areas. Vacancy rate is the single best indicator of rental market tightness — below 3% generally means upward rent pressure; above 5% means tenants have leverage.",
    sources: "Statistics Canada (CMHC rental series)",
  },
  {
    href: "/real-estate/commercial",
    icon: Store,
    title: "Commercial",
    description:
      "Commercial property assessments, business formation rates, retail sales trends, and commercial zoning activity. Useful for understanding which corridors are attracting commercial investment and whether retail or industrial demand is leading the cycle.",
    sources: "Edmonton Open Data, Statistics Canada",
  },
];

export default function RealEstatePage() {
  return (
    <main className="min-h-screen p-4 sm:p-6 max-w-4xl mx-auto space-y-8">
      <PageHeader
        title="Real Estate Intelligence"
        category="realestate"
        icon={<Home size={22} />}
        description="Market data, prospect identification, and development pipeline tracking across Alberta."
      />

      {/* Explainer */}
      <Card>
        <div className="prose-sm space-y-3 text-sm text-muted">
          <p>
            Alberta real estate is <strong className="text-foreground">cyclical and data-rich</strong>.
            Unlike many Canadian markets, Alberta municipalities publish granular property assessment, permit,
            and business licence data through open APIs. This section turns that raw data into actionable intelligence.
          </p>
          <p>
            The flow is designed to match how a real estate professional actually thinks:{" "}
            <strong className="text-foreground">Market Intel</strong> gives you the macro read (is the market hot or cooling?),{" "}
            <strong className="text-foreground">Pipeline</strong> shows what supply is coming,{" "}
            <strong className="text-foreground">Neighbourhoods</strong> zooms into micro-trends, and{" "}
            <strong className="text-foreground">Prospects</strong> surfaces specific opportunities.
          </p>
          <p>
            If you're a realtor, start with Prospects — it's built to help you find listings before they hit MLS.
            If you're an investor, start with Market Intel and Pipeline to get the macro timing right, then drill
            into Neighbourhoods for location selection. For commercial plays, the{" "}
            <strong className="text-foreground">Commercial</strong> page tracks business formation and
            retail activity that often leads commercial property values by 6–12 months.
          </p>
        </div>
      </Card>

      {/* Page grid */}
      <div className="space-y-3">
        {pages.map((page) => (
          <Link key={page.href} href={page.href} className="group block">
            <Card className="transition-colors hover:border-accent/30">
              <div className="flex items-start gap-3">
                <div className="shrink-0 mt-0.5">
                  <page.icon
                    size={18}
                    className="text-muted group-hover:text-accent transition-colors"
                  />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-medium text-foreground group-hover:text-accent transition-colors">
                      {page.title}
                    </h3>
                    <ArrowRight
                      size={14}
                      className="text-muted group-hover:text-accent transition-colors"
                    />
                  </div>
                  <p className="text-sm text-muted mt-1 leading-relaxed">
                    {page.description}
                  </p>
                  <p className="text-[10px] font-mono text-muted/60 mt-2">
                    {page.sources}
                  </p>
                </div>
              </div>
            </Card>
          </Link>
        ))}
      </div>

      {/* Jargon box */}
      <Card>
        <h3 className="text-xs font-medium text-foreground uppercase tracking-wider mb-3">
          Common terms in this section
        </h3>
        <dl className="space-y-2 text-sm">
          <div>
            <dt className="font-medium text-foreground inline">CMHC</dt>
            <dd className="text-muted inline">
              {" "}— Canada Mortgage and Housing Corporation. A federal Crown corporation that insures mortgages
              and publishes housing market data (starts, completions, vacancy rates, rents).
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground inline">Housing starts</dt>
            <dd className="text-muted inline">
              {" "}— The number of new residential units where construction has begun. A leading indicator
              of future supply. Usually reported as a seasonally adjusted annual rate (SAAR).
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground inline">Mill rate</dt>
            <dd className="text-muted inline">
              {" "}— The property tax rate set by a municipality, expressed as dollars of tax per $1,000 of
              assessed value. A mill rate of 10 means you pay $10 in tax for every $1,000 your property is assessed at.
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground inline">Assessment</dt>
            <dd className="text-muted inline">
              {" "}— The value a municipality assigns to a property for tax purposes. Not the same as market
              value, but trends in assessment values closely track market direction.
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground inline">MLS</dt>
            <dd className="text-muted inline">
              {" "}— Multiple Listing Service. The database realtors use to list properties for sale. "Before
              it hits MLS" means identifying likely sellers from public data before they formally list.
            </dd>
          </div>
          <div>
            <dt className="font-medium text-foreground inline">ArcGIS</dt>
            <dd className="text-muted inline">
              {" "}— A geospatial data platform many Alberta municipalities use to publish property, permit,
              and zoning data as queryable REST APIs. It's how we get parcel-level detail.
            </dd>
          </div>
        </dl>
      </Card>
    </main>
  );
}
